### ISSUE TITLE
Transform to ES5 before publishing to npm

### ISSUE THREAD

**Issue by emmenko** [ryanflorence/react-router-async-props#2]
If I install the dep from npm it still has ES6 syntax, causing webpack to fail as it expects all `node_modules` to be vanilla JS because you usually want to exclude those from being transformed by the `6to5-loader`

```
{ test: /(\.js|\.jsx)$/, loaders: ['6to5-loader', 'jsx-loader?harmony'], exclude: /node_modules/ }
```

What do you think? Is there another way to do it?

**Comment by ryanflorence** [comment]
yeah, I need to spend some time making the repo friendlier, I just need a pre-publish hook

**Comment by ryanflorence** [comment]
done, `v0.1.2`

**Comment by emmenko** [comment]
:+1:
